# Generated by Django 5.2.5 on 2025-09-01 14:24

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('planned_quantity', models.DecimalField(decimal_places=3, help_text='Quantidade planejada', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('consumed_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade efetivamente consumida', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Custo unitário no momento da produção', max_digits=10)),
            ],
            options={
                'verbose_name': 'Production Order Item',
                'verbose_name_plural': 'Production Order Items',
                'ordering': ['material__name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('code', models.CharField(help_text='Código único da receita', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nome da receita', max_length=200)),
                ('version', models.CharField(default='1.0', help_text='Versão da receita', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Descrição do processo de produção')),
                ('yield_quantity', models.DecimalField(decimal_places=3, help_text='Quantidade produzida por lote', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('estimated_time_minutes', models.PositiveIntegerField(help_text='Tempo estimado de produção em minutos')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('inactive', 'Inativo'), ('archived', 'Arquivado')], default='draft', help_text='Status da receita', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Observações sobre a receita')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantidade necessária do material', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de utilização na receita')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre o uso do material')),
            ],
            options={
                'verbose_name': 'Recipe Item',
                'verbose_name_plural': 'Recipe Items',
                'ordering': ['order', 'material__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('order_number', models.CharField(help_text='Número único da ordem de produção', max_length=50, unique=True)),
                ('planned_quantity', models.DecimalField(decimal_places=3, help_text='Quantidade planejada para produção', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade efetivamente produzida', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('planned', 'Planejado'), ('approved', 'Aprovado'), ('in_progress', 'Em Produção'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('on_hold', 'Pausado')], default='planned', help_text='Status da ordem de produção', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', help_text='Prioridade da ordem', max_length=10)),
                ('planned_start_date', models.DateTimeField(help_text='Data planejada para início')),
                ('planned_end_date', models.DateTimeField(help_text='Data planejada para conclusão')),
                ('actual_start_date', models.DateTimeField(blank=True, help_text='Data real de início', null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, help_text='Data real de conclusão', null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Custo estimado', max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Custo real', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='Observações')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
