# Generated by Django 5.2.5 on 2025-09-01 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0003_initial'),
        ('production', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Pedido de venda relacionado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='supervisor',
            field=models.ForeignKey(help_text='Responsável pela produção', on_delete=django.db.models.deletion.PROTECT, related_name='supervised_orders', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='material',
            field=models.ForeignKey(help_text='Material consumido', on_delete=django.db.models.deletion.CASCADE, related_name='production_items', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='production_order',
            field=models.ForeignKey(help_text='Ordem de produção', on_delete=django.db.models.deletion.CASCADE, related_name='production_items', to='production.productionorder'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(help_text='Produto que será produzido', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='recipe',
            field=models.ForeignKey(help_text='Receita a ser utilizada', on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.recipe'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='material',
            field=models.ForeignKey(help_text='Material necessário', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(help_text='Receita', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='production.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='productionorderitem',
            unique_together={('production_order', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('product', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='recipeitem',
            unique_together={('recipe', 'material')},
        ),
    ]
