# Generated by Django 5.2.5 on 2025-09-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='complexity',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', help_text='Complexidade da receita', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instruções passo a passo para o preparo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('testing', 'Em Teste'), ('inactive', 'Inativo'), ('archived', 'Arquivado')], default='draft', help_text='Status da receita', max_length=20),
        ),
    ]
