# Generated by Django 5.2.5 on 2025-09-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='production_order',
            field=models.ForeignKey(blank=True, help_text='Ordem de produção relacionada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='production.productionorder'),
        ),
    ]
