# Generated by Django 5.2.5 on 2025-09-01 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Pedido de venda relacionado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(help_text='Unidade de medida', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit_of_measure',
            field=models.ForeignKey(help_text='Unidade de medida', on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='inventory.unitofmeasure'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'category_type')},
        ),
    ]
