# Generated by Django 5.2.5 on 2025-09-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(blank=True, help_text='Número único do pedido de venda', max_length=50, unique=True),
        ),
    ]
