# Generated by Django 5.2.5 on 2025-09-04 17:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesorder_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto padrão (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto item (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
