# Generated by Django 5.2.5 on 2025-09-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_customer_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='sales_representative',
        ),
    ]
